import pandas as pd

class Pitch():
    def __init__(self, csv, inning, top_bottom, at_bat, pitch):
        self.game_data = pd.read_csv(csv)
        self.inning_data = self.game_data[self.game_data['Inning'] == inning]
        self.half_inning_data = self.inning_data[self.inning_data['Top/Bottom'] == top_bottom]
        self.at_bat_data = self.half_inning_data[self.half_inning_data['PAofInning'] == at_bat]
        self.data = self.at_bat_data[self.at_bat_data['PitchofPA'] == pitch]
        self.number = pitch
        self.velocity = self.data['RelSpeed']
        self.vertical = self.data['VertBreak']
        self.induced = self.data['InducedVertBreak']
        self.horizontal = self.data['HorzBreak']
        self.spin = self.data['SpinRate']
        self.axis = self.data['SpinAxis']
        self.tilt = self.data['Tilt']
        self.release_height = self.data['RelHeight']
        self.release_side = self.data['RelSide']
        self.release_extension = self.data['Extension']
        self.auto_type = self.data['AutoPitchType']
        self.tagged_type = self.data['TaggedPitchType']
        self.call = self.data['PitchCall']
        self.location_height = self.data['PlateLocHeight']
        self.location_side = self.data['PlateLocSide']
        self.exit_velocity = self.data['ExitSpeed']
        self.launch_angle = self.data['Angle']
        self.hit_direction = self.data['Direction']
        self.hit_spin = self.data['HitSpinRate']
        self.hit_type = self.data['TaggedHitType']
        self.distance = self.data['Distance']
        self.hang_time = self.data['HangTime']
        self.hit_bearing = self.data['Bearing']
        self.result = self.data['PlayResult']
        self.outs_made = self.data['OutsOnPlay']
        self.runs_scored = self.data['RunsScored']
        self.catcher_velocity = self.data['ThrowSpeed']
        self.catcher_pop = self.data['PopTime']